[profile.default]
optimizer = true
optimizer_runs = 4294967295 #4294967295 100000000
evm_version = 'cancun' #'cancun'
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
ffi = true
# Whether to cache builds or not
cache = true
# The cache directory if enabled
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [ '@solady/=lib/solady/src', "forge-gas-snapshot/=lib/forge-gas-snapshot/src"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
